import { Router } from "express";
import { getRepository } from "typeorm";
import { User } from "../entity/User.entity";
import { validate } from "class-validator";
import { createToken } from "../utils/jwt.utils";
import { compare } from "bcryptjs";
import { Request, Response, NextFunction } from "express";
import { registerValidation } from "../utils/validation.utils";
import { loginValidation } from "../utils/validation.utils";
import { sendEmail } from "../utils/email.utils";
import { sendEmailVerification } from "../utils/email.utils";
import { sendPasswordReset } from "../utils/email.utils";
import { sendPasswordResetVerification } from "../utils/email.utils";
import { sendEmailVerification } from "../utils/email.utils";
import { sendPasswordReset } from "../utils/email.utils";
import { sendPasswordResetVerification } from "../utils/email.utils";
import { sendEmailVerification } from "../utils/email.utils";
import { sendPasswordReset } from "../utils/email.utils";
